version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile 
      context: ./ 
    volumes:
      - /app/node_modules #/app/node_modules는 not mapping.
      - ./:/app # Mapping all file in local storage
    ports:
      - "3001:3000" # port mapping
    stdin_open: true